export {default as Login} from './Login'
export {default as Signup} from './Signup'
export {default as Home} from './Home'
export {default as Dashboard} from './Dashboard'
export {default as Profile} from './Profile'
export {default as QuizPage} from './QuizPage'
export {default as Instructions} from './Instructions'
export {default as Testpage} from './Testpage'
export {default as ResultPage} from './ResultsPage'
export {default as Statistics} from './Statistics'
export {default as QuizComparison} from './QuizComparison'
export{default as QuizResults} from './QuizResults'
export{default as QuizDetails} from './QuizDetails'